### ISSUE TITLE
Match the style of the logo with the menu, and redo the width & margin of #browser

### ISSUE THREAD

**Issue by Crystal-RainSlide** [mozilla/code-coverage#488]
This is a `frontend` issue.

### `.logo`

Match the style of the logo with the menu, vertically centerize the logo, add left margin:

``` SCSS
header {
  div.logo {
    height: $header_height;
    line-height: $header_height;
    margin-left: 10px;
  }
}
```

Maybe:
``` SCSS
// Set a variable
$horizontal_margin: 10px;
// or
margin-left: $header_height * 0.2;
```

### `#browser`

This will work on screens in all size, but I changed the `$small_screen` (it should be at the place of `56ch`) with a relative unit.

``` SCSS
#browser {
  max-width: 56ch;
  margin: 0 auto;
  padding: .5em;
}
```
